# Changes here will be overwritten by Copier
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
- AddSonarCloud_flag
- AddEditorConfig_flag
SelectCommunityFeatures:
- AddCodeConduct_flag
- AddContributing_flag
SelectDocumentationFeatures:
- AddLocalDocumentation_flag
- AddOnlineDocumentation_flag
- AddDevDoc_flag
- AddGitHubActionDocumentation_flag
SelectGitHubActions:
- AddGitHubActionBuild_flag
SelectPublishReleaseFeatures:
- AddChangeLog_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
code_of_conduct_email: g.vandenoord@esciencecenter.nl
copyright_holder: Gijs van den Oord
email: g.vandenoord@esciencecenter.nl
full_name: Gijs van den Oord
github_organization: NLeSC
keywords: dashboard, business information
license: Apachev2
package_name: nlesc_mdash
package_short_description: Dashboard displaying business control information for the
    Netherlands eScience Center
template_profile: recommended
version: 0.1.0
